### PR TITLE
VectorForge Group 12 Submission of Extended Abstract

### PR DESCRIPTION
**Pull request by ExhoParth**

### CODE REVIEW

**Comment by ExhoParth** [comment]
Closes #12

**Comment by ExhoParth** [comment]
Closes #12

**Comment by parth126** [comment]
@ExhoParth why was this pull request closed? I need to merge it to main
Can you please reopen it?

**Comment by parth126** [comment]
I have reopened and merged now. No action needed from your end.

**Comment by parth126** [comment]
This was a late submission and will not be considered for grading.

**Pull request merged**
